# Server Configuration
server.port=8081

#

spring.thymeleaf.mode=HTML
Untracked files:
(use "git add <file>..." to include in what will be committed)
.idea/
target/classes/application-dev.properties



spring.thymeleaf.encoding=UTF-8
