# Configuraci�n de Base de Datos H2 (En memoria)
spring.datasource.url=jdbc:h2:mem:fiscalizacion_db;DB_CLOSE_DELAY=-1
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Configuraci�n JPA/Hibernate para H2
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.H2Dialect

# Consola H2 habilitada en /h2-console
spring.h2.console.enabled=true